# 基礎函數

要知道某個物件的類型(變數或常數)，可以使用type(物件)

In [ ]:
a=7
b=a
type(a)
type(b)
type(58)
type(99.9)
type('abc')

可以將運算子放在等號前面，來結合算術運算與賦值。

以下 a -=3 相當於 a=a-3

In [ ]:
a=95
a -=3
print(a)
b=95
b +=5
print(b)

int( )轉換成整數

float( )轉換成浮點數

str( )轉換成字串

在print函數中可以用\來轉義，常用: \n

In [ ]:
int(True)
float(False)
a='A dog, \nA cat,\nA fish'
print(a)

用[ ]來擷取字元

0開始,1是第二個,-1是最後面,-2是倒數第二個...

字串是不可改變的 (要用函式)

In [ ]:
letters='abcdefghijklmnopqrstuvwxyz'
letters[0]
letters[1]
letters[-1]
letters[-2]
name='Henny'
#name[0]='P' #錯誤
name.replace('H','J') #正確
'J'+name[1:] #正確

使用slice從字串中擷取子字串  [start, end, step]

用len( )來取得長度

用split( )來分割

用join( )來結合

用replace( )來替換

In [ ]:
a='cat, fish, dog, cow, apple, banana'
a.split(',')

['cat', ' fish', ' dog', ' cow', ' apple', ' banana']

用 # 號來註解，並且 python 沒有多行註解

用 \ 號來延續多行 (python會將他們視為同一行)

In [ ]:
abc1='abcdefghijklmnopqrstuvwxyz'
abc2='abcdefg'+'hijklmno'+\
'pqrstuvwxyz'
print(abc1)
print(abc2)

abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz

階層、排列、組合

https://tw.from-locals.com/python-math-factorial-permutations-combinations/

In [ ]:
import math
print(math.factorial(3))

6

商數 a // b

餘數 a % b

In [ ]:
a=10
b=3
print(a // b)
print(a % b)

3
1

數字轉換成二進制

In [ ]:
n=11
n=bin(n) #轉換後前面會多0b兩個字後面才是轉換後的二進制數字
a=n[2:] #把0b丟掉

多行註解

用「三個雙引號 """ 或三個單引號 '''」做多行註解

In [ ]:
# 井字號後面可以寫一行的註解
'''
這裡是多行註解，
不影響程式執行的結果。
'''
print('Hello, World!')   # 單行註解也可以寫在程式碼後方

# list 串列 (可變更)

用 [ ] 或 list( ) 建立

In [ ]:
#建立list
empty_list1=[]
empty_list2=list()
a=['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
#將其他資料轉換成list
list('fish')
a_tuple=('ready', 'fire', 'aim')
list(a_tuple)

使用 [ index ] 來取得 list 中的值

In [ ]:
marxes=['Groucho', 'Chico', 'Harpo']
marxes[0]
marxes[-1]
bird=[marxes, 'brid']
bird[0][2]='frog'
bird

[['Groucho', 'Chico', 'frog'], 'brid']

將串列反過來的技巧

[開始:結束:間隔]

In [ ]:
marxes=['Groucho', 'Chico', 'Harpo']
marxes[0:2]
marxes[::-1]

['Harpo', 'Chico', 'Groucho']

在串列中增加值 append( )、extend( )、insert( )

In [ ]:
marxes=['Groucho', 'Chico', 'Harpo']
other=['Gummo', 'Karl']
marxes.append('Zeppo')
marxes.append(other)
marxes.extend(other)
marxes.insert(0,'other')
marxes

在串列中刪除值

del( ) 根據index

remove( ) 根據元素值

pop( ) 根據index

In [ ]:
marxes=['Groucho', 'Chico', 'Harpo', 'Gummo', 'Karl']
del marxes[-1]
marxes.remove('Harpo')
marxes.pop(-1)
marxes

['Groucho', 'Chico']

用 list.index(obj) 來尋找list中obj的index

用 in( )來測試值是否在 list 中

用 count( )來計算出現次數

用 sorted( A ) 複製一份來排序，不改變A的元素

用 A.sort( ) 直接改變A的元素排序

用 = 來指派， 用 copy( )、list( )、slice [:] 來複製

In [ ]:
a=[1, 2, 3]
b=a
c=a.copy()
d=list(a)
e=a[:]
a[0]='Which one change?'
print(a,b,c,d,e)

用 range(start, end) 產生數列

In [ ]:
print(range(0,10))
print(list(range(0, 10)))

range(0, 10)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Tuple (不可變更)

用 ( ) 來建立 tuple

或賦值後給逗點,來建立tuple

tuple( ) 可以將其他東西轉換成tuple

In [ ]:
empty_tuple=() #空的tuple
empty_tuple
one_tuple=(1) #沒逗點是數字
type(one_tuple)
one_tuple=(1,) #有逗點才會是tuple
type(one_tuple)
marx='Groucho'
type(marx)
marx='Groucho',
type(marx)
marx
marxs='Groucho', 'Chico', 'Harpo' #最後一筆不用逗點
print(marxs)
a, b, c= marxs
print(a)
print(b)
print(c)

# dictionary 字典 (dict)

字典與串列很像，但他不在乎項目的順序，而且通常不會用到0、1等index來選擇項目。

你必須為每一個值指定一格獨一無二的鍵(Key)

用 { } 來建立字典

用 dict( ) 來轉換

'Key' : 'Value'

In [ ]:
empty_dict={}
fruit={
    'a':'apple',
    'b':'banana',
    'w':'watermelon'
}
print(fruit)
lol=[ ['a','b'], ['c','d'], ['e','f'] ]
dict(lol)

{'a': 'apple', 'b': 'banana', 'w': 'watermelon'}

{'a': 'b', 'c': 'd', 'e': 'f'}

用 [ Key ] 來添加或變更項目

用 [ Key ] 來取得一個項目

用 keys( ) 來取得所有的 key

用 values( ) 來取得所有的值

用 items( ) 來取得所有的 鍵/值

用 update( ) 來合併字典

用 del( ) 與 [ Key ] 來刪除項目

用 clear( ) 來刪除所有項目

用 in( ) 來測試 Key

用 = 來指派， 用 copy( ) 來複製

In [ ]:
fruit={
    'a':'apple',
    'b':'banana',
    'w':'watermelon'
}
fruit['c']='herry'
print(fruit)
fruit['c']='cherry'
fruit

{'a': 'apple', 'b': 'banana', 'w': 'watermelon', 'c': 'herry'}

{'a': 'apple', 'b': 'banana', 'w': 'watermelon', 'c': 'cherry'}

建立 A-Z 對應 1-26 的 dictionary

In [ ]:
import string
A_to_Z=dict(zip(string.ascii_uppercase, range(1,27)))
a_to_z=dict(zip(string.ascii_lowercase, range(1,27)))

# Array

產生 Array 的函數:  np.array(  這裡輸入 list  )


若想把 x= [3,6,9] 裡面的每個元素都乘 3 變成 [9,18,27]

用 list  x*3  會印出3次   [3,6,9,3,6,9,3,6,9]

In [ ]:
x=[3, 6, 9]
print(x*3)

import numpy as np
y=np.array(x)
print(y*3)

Array 一樣可以用 index 呼叫

In [ ]:
print(y[:])
print(y[0])
print(y[0:2])

多維 Array 可建立出矩陣

m = np.array( [ [1,2,3],[4,5,6] ] )

用[ ] 包住 每一行的元素 [ ]

這是一個  2乘3 的矩陣

用shape指令 可以確認維度

print(np.shape(m))

In [ ]:
m = np.array( [ [1,2,3],[4,5,6] ] )
print(m)
print(np.shape(m))
print(m[0,0])   ## 1st row ,1st column
print(m[1,2])   ## laster

[[1 2 3]
 [4 5 6]]
(2, 3)
1
6

Array 常用 function

np.reshape()  ## 把矩陣的行列改變

np.eye()    ## 單位矩陣

矩陣.T ##轉置矩陣

矩陣.I ##反矩陣

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])   ## 本來是1*1
b=np.reshape(a,(2,-1) ) # 利用 reshape 改成 2*2
#### 這邊的參數很重要  (2,-1)
#### 可以想成 我要生成 2* X 的矩陣 X 是未知的
#### X 寫 -1 的話 Python 會自己抓 X 是多少
np.eye(3)

# Set 集合

集合就像是被移除vauue值，只留下key鍵的字典，並且每個鍵都是獨一無二，當你想知道某個東西是否存在時，可以使用集合。

以 set( ) 來建立

或是將一個或多個以逗號分隔的值包在一個大括號內

In [ ]:
empty_set=set()
type(empty_set)
even={0, 2, 4, 6, 8}
odd={1, 3, 5, 7, 9}
set('letter') #重複值會被刪掉，只在乎有或沒有

{'e', 'l', 'r', 't'}

集合運算

交集 &、 intersection( )

聯集 |、 union( )

差集 -、 difference( )

#邏輯判斷與迴圈

if else 判斷式

In [ ]:
color='puce'
if color == 'red':
  print("It's a tomato")
elif color == 'green':
  print("It's a green pepper")
elif color == 'bee purple':
  print("I dont know what it is, but only bees can see it")
else:
  print("I've never heard of the color", color, "before")

布林值 and or not

In [ ]:
x=7
print(5<x)
print(x>10)
print(5<x<10)
print(5<x and x<10)
print(5<x and x>10)
print(5<x and not x>10)

for 迴圈

In [ ]:
#數字
abc=[0, 1, 2]
for x in abc:
   print(x)

#文字
theBeatles = ['John Lennon', 'Paul McCartney', 'Ringo Starr', 'George Harrison']
print(range(len(theBeatles)))
for i in range(len(theBeatles)):
    print(theBeatles[i])

for j in range(5):
  print(j)

0
1
2
range(0, 4)
John Lennon
Paul McCartney
Ringo Starr
George Harrison

while 迴圈

用 break 來取消

用 continue 來跳過

In [ ]:
count=1
while count <= 5 :
  print(count)
  count += 1

In [ ]:
while True:
  value = input("Interger, please [type q to quit]: ")
  if value == 'q':
    break
  number=int(value)
  if number % 2 == 0: # an even number
    continue
  print(number, "squared is", number**2 )

In [ ]:
nums=[1, 3, 5, 10]
position=0
while position < len(nums):
  n=nums[position]
  if n % 2 == 0:
    print("Find the even number", n)
    break
  position += 1
else:
  print("No even number found")

In [ ]:
rabbits=['Flopsy', 'Mopsy', 'Copsy', 'Peter']
for anyword in rabbits:
  print(anyword)

Flopsy
Mopsy
Copsy
Peter

用 zip( ) 來迭代多個序列

In [ ]:
day=['Mon', 'Tue', 'Wed']
fruit=['apple', 'banana', 'orenge']
drink=['Tea', 'coffee', 'beer']
for day, fruit, drink in zip(day, fruit, drink):
  print(day, ': drink', drink, 'and eat', fruit)

Mon : drink Tea and eat apple
Tue : drink coffee and eat banana
Wed : drink beer and eat orenge

#Dataframe

下載Pandas

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

Import pandas as pd

建立dict並轉換成dataframe

更改欄位以及索引名稱

df.rename( )可以重新命名單一欄位的名稱

https://www.learncodewithmike.com/2020/11/python-pandas-dataframe-tutorial.html

In [ ]:
import pandas as pd

#建立dictionary key:value
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

#用這個dict轉換成df, key是colum name, value是data
df = pd.DataFrame(grades)
print(df)

#更改欄位以及索引名稱
df.index = ["s1", "s2", "s3", "s4"]  #自訂索引值
df.columns = ["student_name", "math_score", "chinese_score"]  #自訂欄位名稱
print(df)

#用rename函數將name改為customer
df.rename(columns={'name': 'customer'})



df.index = [0, 1, 2, 3]  #自訂索引值
df.columns = ["name", "math", "chinese"]

     name  math  chinese
0    Mike    80       63
1  Sherry    75       90
2   Cindy    93       85
3    John    86       70
   student_name  math_score  chinese_score
s1         Mike          80             63
s2       Sherry          75             90
s3        Cindy          93             85
s4         John          86             70

head( ) 抓取前幾筆資料

tail( ) 抓取後幾筆資料

用[ ]抓取資料

In [ ]:
print(df.head(2))
print(df.tail(2))

print("=================================")

print("取得單一欄位資料(型別為Series)")
print(df["name"])

print("=================================")

print("取得單一欄位資料(型別為DataFrame)")
print(df[["name"]])

print("=================================")

print("取得多欄位資料(型別為DataFrame)")
print(df[["name", "chinese"]])

print("=================================")

print("取得索引值0~2的資料")
print(df[0:3])

at [資料索引值,欄位名稱]：利用資料索引值及欄位名稱來取得「單一值」

iat [資料索引值,欄位順序]：利用資料索引值及欄位順序來取得「單一值」

loc [資料索引值,欄位名稱]：利用資料索引值及欄位名稱來取得「資料集」

iloc[資料索引值,欄位順序]：利用資料索引值及欄位順序來取得「資料集」

In [ ]:
#at
print("利用at()方法取得索引值為1的math欄位資料")
print(df.at[1, "math"])

print("=================================")

#iat
print("利用iat()方法取得索引值為1的第一個欄位資料")
print(df.iat[1, 0])

print("=================================")

#loc
print("取得資料索引值為1和3的name及chinese欄位資料集")
print(df.loc[[1, 3], ["name", "chinese"]])

print("=================================")

#iloc
print("取得資料索引值為1和3的第一個及第三個欄位資料集")
print(df.iloc[[1, 3], [0, 2]])


#補充loc抓出來後的資料型態
#想要判斷content欄位中的資料長度有大於15的話需要加上.str，否則會判斷成content這個欄位有幾個列的長度
return tweets.loc[ tweets['content'].str.len()>15 , ['tweet_id'] ] #這個抓取出來是dataframe
return tweets.loc[ tweets['content'].str.len()>15 , 'tweet_id' ] #這個抓取出來是pandas中的series(物件)

In [ ]:
import pandas as pd

data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6]
}

df = pd.DataFrame(data)

# 選取第一行
first_row = df.iloc[0]

# 選取第一列
first_column = df.iloc[:, 0]

# 選取前兩行和前兩列
subset = df.iloc[:2, :2]

# df.iloc[1]：這將返回 DataFrame 中索引為 1 的行，返回的是 Series。
# df.iloc[1:2]：這將返回索引範圍為 1 到 2（不包括 2）的行，返回的是包含選取行的 DataFrame。

在dataframe中想要抓取其中幾個欄位

In [ ]:
import pandas as pd

# 假設你有一個名為 df 的 DataFrame，其中包含 x1 到 x5 五個列
data = {'x1': [1, 2, 3],
        'x2': [4, 5, 6],
        'x3': [7, 8, 9],
        'x4': [10, 11, 12],
        'x5': [13, 14, 15]}

df = pd.DataFrame(data)

# 選取 x2 和 x5 列，並建立一個新的 DataFrame
selected_columns = ['x2', 'x5']
new_df = df[selected_columns]

print(new_df)
print("=================================")

# 直接用df呼叫需要用兩個 [[ ]]
new_df1=df[['x2', 'x5']]
print(new_df1)

   x2  x5
0   4  13
1   5  14
2   6  15
=================================
   x2  x5
0   4  13
1   5  14
2   6  15

len() 函數可以計算行數

shape[] 函數可以用來計算行數或列數

In [ ]:
x=pd.DataFrame({
    'category': ['Low Salary', 'Average Salary', 'High Salary'],
    'accounts_count': [
        accounts[accounts.income < 20000].shape[0],
        accounts[(accounts.income >= 20000) & (accounts.income <= 50000)].shape[0],
        accounts[accounts.income > 50000].shape[0],
    ],
})
print(x)

groupby( ) 可以對資料進行分組

In [ ]:
data = {
    'emp_id': [1, 1, 1, 2, 2],
    'event_day': ['2020-11-28', '2020-11-28', '2020-12-03', '2020-11-28', '2020-12-09'],
    'in_time': [4, 55, 1, 3, 47],
    'out_time': [32, 200, 42, 33, 74]
}

employees = pd.DataFrame(data)

employees['total_time']=employees['out_time']-employees['in_time']
employees=employees.loc[:, ['event_day', 'emp_id', 'total_time']]
group=employees.groupby(['event_day','emp_id']).sum().reset_index()
print(group)

In [ ]:
import pandas as pd

data = {
    'sell_date': ['2020-05-30', '2020-06-01', '2020-06-02', '2020-05-30', '2020-06-01', '2020-06-02', '2020-05-30'],
    'product': ['Headphone', 'Pencil', 'Mask', 'Basketball', 'Bible', 'Mask', 'T-Shirt']
}

activities = pd.DataFrame(data)

activities=activities.drop_duplicates().sort_values('product')
grouped = activities.groupby('sell_date').agg(num_sold=('product', 'size'), products=('product', ','.join)).reset_index() #groupby後想做兩件事以上可以用agg()
print(grouped)

新增Dataframe欄位與資料

直接用[]新增欄位

insert( )：在指定的欄位位置新增欄位資料

append()：新增一筆或一列的資料，透過傳入字典(Dictionary)來指定各欄位的值，並且會回傳一個新的Pandas DataFrame資料集

In [ ]:

# Create a new column 'bonus' with default value 0
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}
df = pd.DataFrame(grades)
df['bonus'] = 0

#insert
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

#用這個dict轉換成df, key是colum name, value是data
df = pd.DataFrame(grades)

df.insert(2, column="engilsh", value=[88, 72, 74, 98])
print("在第三欄的地方新增一個欄位資料")
print(df)


print("=================================")


#append
#建立dictionary key:value
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

#用這個dict轉換成df, key是colum name, value是data
df = pd.DataFrame(grades)

new_df = df.append({
    "name": "Henry",
    "math": 60,
    "chinese": 62
}, ignore_index=True)

print("新增一筆資料")
print(new_df)

concat( )：利用合併多個Pandas DataFrame的方式來新增資料，並且會回傳一個新的Pandas DataFrame資料集

In [ ]:
#concat
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

df1 = pd.DataFrame(grades)
print("原來的df")
print(df1)

print("=================================")

df2 = pd.DataFrame({
    "name": ["Henry"],
    "math": [60],
    "chinese": [62]
})

new_df = pd.concat([df1, df2], ignore_index=True)
print("合併df來新增資料")
print(new_df)

原來的df
     name  math  chinese
0    Mike    80       63
1  Sherry    75       90
2   Cindy    93       85
3    John    86       70
=================================
合併df來新增資料
     name  math  chinese
0    Mike    80       63
1  Sherry    75       90
2   Cindy    93       85
3    John    86       70
4   Henry    60       62

修改或刪除Pandas DataFrame資料

使用index[ ]修改df資料

drop(欄位名稱串列,axis=1)：刪除指定欄位名稱的欄位，並且會回傳一個新的Pandas DataFrame資料集 (axis=1是colum,0是row)

In [ ]:
#修改df資料
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

df = pd.DataFrame(grades)

print("原來的df")
print(df)

print("=================================")

df.at[1, "math"] = 100  #修改索引值為1的math欄位資料
df.iat[1, 0] = "Larry"  #修改索引值為1的第一個欄位資料
print("修改後的df")
print(df)

print("=================================")

#刪除df資料
new_df = df.drop(["math"], axis=1)
print("刪除math欄位")
print(new_df)

print("=================================")
new_df1 = df.drop([0, 3], axis=0)  # 刪除第一筆及第四筆資料
print("刪除第一筆及第四筆資料")
print(new_df1)

刪除含有NA的資料

dropna( )：刪除含有NaN或空值的資料，並且會回傳一個新的Pandas DataFrame資料集，在進行資料清理的時候非常實用

drop_duplicates( )：刪除重複的資料，並且會回傳一個新的Pandas DataFrame資料集，同樣最常應用在資料清理的時候，想要針對特定欄位時候可以用 subset=['salary']

https://zhuanlan.zhihu.com/p/116884554

In [ ]:
import pandas as pd
import numpy as np

#dropna
grades = {
    "name": ["Mike", "Sherry", np.NaN, "John"],
    "city": ["Taipei", np.NaN, "Kaohsiung", "Taichung"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

df = pd.DataFrame(grades)
print("原來的df")
print(df)

print("======================================")

new_df = df.dropna()
print("刪除空值後的df")
print(new_df)

print("============================================================================")

#drop_duplicates
grades = {
    "name": ["Mike", "Mike", "Cindy", "John"],
    "city": ["Taipei", "Taipei", "Kaohsiung", "Taichung"],
    "math": [80, 80, 93, 86],
    "chinese": [80, 80, 93, 86]
}

df = pd.DataFrame(grades)
print("原來的df")
print(df)

print("======================================")

new_df = df.drop_duplicates()
print("刪除重複值後的df")
print(new_df)

原來的df
     name       city  math  chinese
0    Mike     Taipei    80       63
1  Sherry        NaN    75       90
2     NaN  Kaohsiung    93       85
3    John   Taichung    86       70
======================================
刪除空值後的df
   name      city  math  chinese
0  Mike    Taipei    80       63
3  John  Taichung    86       70
============================================================================
原來的df
    name       city  math  chinese
0   Mike     Taipei    80       80
1   Mike     Taipei    80       80
2  Cindy  Kaohsiung    93       93
3   John   Taichung    86       86
======================================
刪除重複值後的df
    name       city  math  chinese
0   Mike     Taipei    80       80
2  Cindy  Kaohsiung    93       93
3   John   Taichung    86       86

篩選Pandas DataFrame資料

利用中括號[ ]存取欄位來進行資料篩選

In [ ]:
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

df = pd.DataFrame(grades)

print("原來的df")
print(df)

print("=================================")

print("篩選math大於80的資料集")
print(df[df["math"] > 80])

利用 isin( ) 找出包含特定值的資料集

In [ ]:
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

df = pd.DataFrame(grades)

print("原來的df")
print(df)

print("=================================")

print("篩選name欄位包含John的資料集")
print(df[df["name"].isin(["John"])])

原來的df
     name  math  chinese
0    Mike    80       63
1  Sherry    75       90
2   Cindy    93       85
3    John    86       70
=================================
篩選name欄位包含John的資料集
   name  math  chinese
3  John    86       70

用contain來抓取特定資料

In [ ]:
users[users['mail'].str.contains('@leetcode.com')]

排序Pandas DataFrame資料

sort_index( )：依照索引值來進行排序，並且會回傳一個新的Pandas DataFrame資料集

sort_values( )：依照欄位內容來進行排序，並且會回傳一個新的Pandas DataFrame資料集

rank(method='dense', ascending=False) 用於在一個 DataFrame 或 Series 中計算數據的排名。

In [ ]:
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

df = pd.DataFrame(grades)
df.index = ["s3", "s1", "s4", "s2"]  # 自訂資料索引值

print("原來的df")
print(df)

print("============================")

new_df = df.sort_index(ascending=True) #依照index遞增
print("遞增排序")
print(new_df)

print("============================")

new_df = df.sort_index(ascending=False) #依照index遞減
print("遞減排序")
print(new_df)

In [ ]:
grades = {
    "name": ["Mike", "Sherry", "Cindy", "John"],
    "math": [80, 75, 93, 86],
    "chinese": [63, 90, 85, 70]
}

df = pd.DataFrame(grades)

print("原來的df")
print(df)

print("============================")

new_df = df.sort_values(["math"], ascending=True) #依照math分數大小遞增
print("遞增排序")
print(new_df)

print("============================")

new_df = df.sort_values(["math"], ascending=False) #依照math分數大小遞減
print("遞減排序")
print(new_df)

In [ ]:
import pandas as pd

# 假設這是您的三個列表
ids = [1, 2, 3, 4, 5, 6]
scores = [3.50, 3.65, 4.00, 3.85, 4.00, 3.65]

# 將列表組合成 DataFrame
data = {'id': ids, 'score': scores}
scores = pd.DataFrame(data)
print(scores)

# Use the rank method to assign ranks to the scores in descending order with no gaps
scores['rank'] = scores['score'].rank(method='dense', ascending=False)

# Drop id column & Sort the DataFrame by score in descending order
result_df = scores.drop('id',axis=1).sort_values(by='score', ascending=False)

print(result_df)

用apply新增資料做變數篩選

Python 功能讀取一行（Row）pandas dataframe 的數據，並輸出該行在新列（Column）的值。

In [ ]:
import pandas as pd
df = pd.DataFrame(
    {
      'Name':   ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O'],
      'Sex':    ['M', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'F', 'M', 'M', 'M', 'F', 'M', 'M'],
      'Age':    [38, 28, 31, 34, 28, 28, 36, 33, 22, 39, 22, 24, 31, 29, 22],
      'Height': [1.74, 1.51, 1.67, 1.87, 1.8, 1.51, 1.85, 1.89, 1.81, 1.72, 1.75, 1.64, 1.9, 1.62, 1.61],
      'Weight': [45, 63, 39, 45, 67, 66, 53, 45, 72, 46, 58, 44, 73, 70, 51],
    }
)
print(df)

# apply用法
df_eg1 = df.copy()
def BMI_2(weight, height): #先建立一個計算BMI的函數
  return round(weight / (height ** 2), ndigits=2)

#將apply用於計算df_eg1中每一列資料的BMI
df_eg1['BMI_apply2'] = df_eg1.apply(lambda r: BMI_2(r['Weight'],r['Height']), axis=1) #這裡的r代表df_eg1的每一列資料，類似遞迴依序往下
print(df_eg1)

   Name Sex  Age  Height  Weight
0     A   M   38    1.74      45
1     B   M   28    1.51      63
2     C   M   31    1.67      39
3     D   F   34    1.87      45
4     E   F   28    1.80      67
5     F   M   28    1.51      66
6     G   F   36    1.85      53
7     H   M   33    1.89      45
8     I   F   22    1.81      72
9     J   M   39    1.72      46
10    K   M   22    1.75      58
11    L   M   24    1.64      44
12    M   F   31    1.90      73
13    N   M   29    1.62      70
14    O   M   22    1.61      51
   Name Sex  Age  Height  Weight  BMI_apply2
0     A   M   38    1.74      45       14.86
1     B   M   28    1.51      63       27.63
2     C   M   31    1.67      39       13.98
3     D   F   34    1.87      45       12.87
4     E   F   28    1.80      67       20.68
5     F   M   28    1.51      66       28.95
6     G   F   36    1.85      53       15.49
7     H   M   33    1.89      45       12.60
8     I   F   22    1.81      72       21.98
9     J   M   39    1.72      46       15.55
10    K   M   22    1.75      58       18.94
11    L   M   24    1.64      44       16.36
12    M   F   31    1.90      73       20.22
13    N   M   29    1.62      70       26.67
14    O   M   22    1.61      51       19.68

正則表達式 re https://ithelp.ithome.com.tw/articles/10220711

r'' : 表示原始字串並且在''中所出現的所有符號都符合正則表達式

^[A-Za-z] ：的^表示字串開始位置定錨且開頭位置只能是[A-Za-z]的英文字

[A-Za-z0-9_\.\-]* ：表示接著可以包含零個或多個字母、數字、底線 _、句號 . 或破折號 -。

@leetcode ：表示字面字符串 @leetcode

\. : 正則表達是中.有特殊意義所以如果要讓他判斷字串內含有.的話要加上反斜線

com$ : 表示最後以com結尾

In [ ]:
valid=users[ users['mail'].str.match( r'^[a-zA-Z][a-zA-Z0-9_.-]*@leetcode\.com$' ) ]